import { ThemeProvider } from "@/components/dashboard/theme-provider";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Dashboard from "@/components/dashboard/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Dashboard>{children}</Dashboard>
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
